# Generated by Django 2.0 on 2017-12-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicterms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docid',
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(default='This document still needs text.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='topic_documents',
            field=models.ManyToManyField(related_name='topic_terms', to='topicterms.Document'),
        ),
    ]
