# Generated by Django 2.0 on 2017-12-22 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicterms', '0002_auto_20171221_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='term',
            name='topic_documents',
        ),
        migrations.AddField(
            model_name='document',
            name='annotator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicterms',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topicterms.Document'),
        ),
        migrations.AddField(
            model_name='topicterms',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topicterms.Term'),
        ),
        migrations.AddField(
            model_name='topicterms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
