# Generated by Django 2.0 on 2018-02-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicterms', '0005_document_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='complete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
