# Generated by Django 2.0 on 2018-03-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicterms', '0006_auto_20180222_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['term']},
        ),
        migrations.AddField(
            model_name='document',
            name='index',
            field=models.CharField(default='missing', max_length=100),
            preserve_default=False,
        ),
    ]
