# Generated by Django 2.0 on 2018-05-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicterms', '0007_auto_20180302_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTerms',
            fields=[
                ('term_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topicterms.Term')),
            ],
            bases=('topicterms.term',),
        ),
    ]
