# Generated by Django 2.0 on 2018-06-02 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicterms', '0008_qualityterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityterms',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualityterms',
            name='document',
            field=models.ForeignKey(default=4395, on_delete=django.db.models.deletion.CASCADE, to='topicterms.Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualityterms',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
