# Generated by Django 2.0 on 2018-06-02 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicterms', '0009_auto_20180602_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicterms.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='qualityterms',
            name='document',
        ),
        migrations.RemoveField(
            model_name='qualityterms',
            name='term_ptr',
        ),
        migrations.RemoveField(
            model_name='qualityterms',
            name='user',
        ),
        migrations.DeleteModel(
            name='QualityTerms',
        ),
    ]
