# Generated by Django 2.0 on 2018-06-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topicterms', '0010_auto_20180602_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitycheck',
            old_name='correct',
            new_name='checked',
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='topicterms.Term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topicterms.Document'),
        ),
    ]
