# Generated by Django 2.0 on 2018-06-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicterms', '0012_auto_20180622_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='skippable',
            field=models.BooleanField(default=True),
        ),
    ]
