# Generated by Django 2.0 on 2018-07-24 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicterms', '0013_document_skippable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skippable', models.BooleanField(default=True)),
                ('complete', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='annotator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='document',
            name='skippable',
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicterms.Document'),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
